---
title: "Física - Discussão Projeto I"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(comment = "*")
knitr::opts_chunk$set(fig.width=3)
knitr::opts_chunk$set(fig.height=2)
knitr::opts_chunk$set(fig.align="center")

library(gridExtra)
library(grid)
library(latex2exp)
library(ggplot2)
library(polynom)
```

```{r include=FALSE}
# Setup tableGrob theme with text parsing
tt <- ttheme_default(colhead=list(fg_params = list(parse=TRUE)))

math = function(s) { paste0("$", s, "$") }
parens = function(s) { paste0("(", s, ")") }
subscript = function(s, v) { math(paste0(s, "_{", v, "}")) }
flatten_by_rows = function(m) { c(t(m)) }
rad2deg <- function(rad) {(rad * 180) / (pi)}
deg2rad <- function(deg) {(deg * pi) / (180)}
polys <- function(p, s) { gsub("x", s, as.character(p)) }

ph.TeX.energia = math("J")
ph.TeX.deslocamento = math("m")
ph.TeX.velocidade = math("m/s")
ph.TeX.tempo = math("s")
ph.TeX.aceleracao = math("m/s^2")
ph.TeX.massa = math("kg")
ph.TeX.forca = math("N")
ph.TeX.potencia = math("W")
```


### Parâmetros dos experimentos

```{r}
p.massa = 0.2107
p.regua = 2

# Posição inicial do fim da bandeira
p.bandeira = 0.204

# Tamanho da bandeira
p.tam_bandeira = 0.0975

# Distância entre sensores adjacentes
p.MRU.distancias = c(0.373, 0.322, 0.655, 0.37)
p.MRU.posicoes = cumsum(p.MRU.distancias) - p.bandeira


p.MUV.distancias = c(0.207 + p.bandeira, 0.414, 0.427, 0.49)
p.MUV.posicoes = cumsum(p.MUV.distancias) - p.bandeira
p.MUV.h = function(s = 0) { 0.012 * (p.regua - p.bandeira - s) / p.regua }

p.MUV_flag.distancias = c(0.406, 0.49, 0.354, 0.495)
p.MUV_flag.posicoes = cumsum(p.MUV.distancias) - p.bandeira
p.MUV_flag.h = function(s = 0) { 0.005 * (p.regua - p.bandeira - s) / p.regua }
```


### Dados dos experimentos

Os dados dos experimentos MU e MUV já foram carregados a partir de arquivos `.csv`.

```{r}
dados.MRU = read.csv("mru.csv")
dados.MUV = read.csv("muv.csv")
dados.MUV_flag = read.csv("muv_flag.csv")
```

```{r, fig.height=2, echo=FALSE}
colnames(dados.MRU) = TeX(paste(subscript("t", 1:ncol(dados.MRU)), parens(ph.TeX.tempo)))
grid.arrange(top="Observações - MRU", tableGrob(dados.MRU, theme=tt))
```
```{r, fig.height=1, echo=FALSE}
colnames(dados.MUV) = TeX(paste(subscript("t", 1:ncol(dados.MUV)), parens(ph.TeX.tempo)))
grid.arrange(top="Observações - MUV", tableGrob(dados.MUV, theme=tt))
```
```{r, fig.height=2, echo=FALSE}
colnames(dados.MUV_flag) = TeX(paste(subscript("t", 1:ncol(dados.MUV_flag)), parens(ph.TeX.tempo)))
grid.arrange(top="Observações - MUV (bandeira)", tableGrob(dados.MUV_flag, theme=tt))
```

### Funções e constantes
```{r}
# Constantes comuns (physics)
ph.G = 9.7833

# Funções comuns (physics)
ph.peso = function(m, g = ph.G) { m*g }
ph.e.potencial = function(m, h, g = ph.G) { m*g*h }
ph.e.cinetica = function(v, m) { 0.5*m*v^2 }
ph.trabalho = function(f, dx, theta) { f*dx*theta }

# Funções MRU
MRU.velocidade = function(ds, dt) { ds/dt }
MRU.deslocamento = function(v, t) { v*t }

# Funções MUV
MUV.velocidade = function(a, t, v0 = 0) { v0 + a*t }
MUV.deslocamento = function(a, t, v0 = 0) { t*v0 + 0.5*a*t^2 }
MUV.aceleracao = function(s, t, v0 = 0) { 2*(s - t*v0)/t^2 }
```

### Análises gráficas

#### MRU

```{r, fig.width=5, fig.height=3.5, echo=FALSE}
rep_posicoes = rep(p.MRU.posicoes, times=nrow(dados.MRU))
x = flatten_by_rows(dados.MRU)
reg = lm(rep_posicoes ~ x)

x_curve = data.frame(x=seq(0.0, 2.0, length.out=30))
predicted = predict(reg, x_curve, interval="confidence")
reg_curve = polynomial(coef(reg))
curve_text = paste("Curva:", polys(round(reg_curve, digits=3), "t"))

grid.arrange(
  top="Deslocamento x Tempo",
  ggplot(mapping=aes(x=x)) 
    + geom_point(aes(y=rep_posicoes))
    + geom_line(aes(x=x_curve, y=predicted[,"fit"]))
    + geom_ribbon(aes(x=x_curve, ymin=predicted[,"lwr"], ymax=predicted[,"upr"]), alpha=0.15)
    + geom_text(aes(x=0.1, y=1.8, label=curve_text, hjust=0.0, vjust=0), parse=TRUE)
    + ylab(TeX(paste("Deslocamento", parens(ph.TeX.deslocamento))))
    + xlab(TeX(paste("Tempo", parens(ph.TeX.tempo))))
    + xlim(c(0.0, 2.0))
    + ylim(c(0.0, 2.0))
  )
```

```{r, fig.width=9, fig.height=3.5, echo=FALSE}
velocidades = t(MRU.velocidade(p.MRU.posicoes, t(dados.MRU)))
colnames(velocidades) = TeX(paste(subscript("v", 1:ncol(dados.MRU)), parens(ph.TeX.velocidade)))

y = flatten_by_rows(velocidades)
x = flatten_by_rows(dados.MRU)
reg = lm(y ~ x)
reg_curve = polynomial(coef(reg))
curve_text = paste("Curva:", polys(round(reg_curve, digits=3), "t"))

x_curve = data.frame(x=seq(0.0, 2.0, length.out=20))
predicted = predict(reg, x_curve, interval="confidence") 

grid.arrange(
  top="Velocidade x Tempo",
  nrow=1,
  tableGrob(round(velocidades, digits=2), theme=tt),
  ggplot(mapping=aes(x=x)) 
    + geom_point(aes(y=y))
    + geom_line(aes(x=x_curve, y=predicted[,"fit"]))
    + geom_text(aes(x=0.1, y=1.8, label=curve_text, hjust=0.0, vjust=0), parse=TRUE)
    + geom_ribbon(aes(x=x_curve, ymin=predicted[,"lwr"], ymax=predicted[,"upr"]), alpha=0.15)
    + ylab(TeX(paste("Velocidade", parens(ph.TeX.velocidade))))
    + xlab(TeX(paste("Tempo", parens(ph.TeX.tempo))))
    + xlim(c(0.0, 2.0))
    + ylim(c(0.0, 2.0))
  )
```

#### MUV

```{r, fig.width=6, fig.height=3.5, echo=FALSE}
# Analise de deslocamento
rep_posicoes = rep(p.MUV.posicoes, times=nrow(dados.MUV))

x = flatten_by_rows(dados.MUV)
reg = lm(rep_posicoes ~ 0 + I(x^2))

curve = polynomial(c(0, 0, coef(reg)))
x_curve = data.frame(x=seq(0.0, 8.0, length.out=30))
predicted = predict(reg, x_curve, interval="confidence")

label_points = round(rep_posicoes, digits=2)
curve_text = paste("Deslocamento:", polys(round(curve, digits=3), "t"))

grid.arrange(
  top="Deslocamento x Tempo",
  nrow=1,
  ggplot(mapping=aes(x=x)) 
    + geom_point(aes(y=rep_posicoes))
    + geom_line(aes(x=x_curve, y=predicted[,"fit"]))
    + geom_ribbon(aes(x=x_curve, ymin=predicted[,"lwr"], ymax=predicted[,"upr"]), alpha=0.15)
    + geom_text(aes(y=rep_posicoes, label=label_points, hjust=0.7, vjust=-1.4))
    + geom_text(aes(x=0.5, y=2.0, label=curve_text, hjust=0.0, vjust=0), parse=TRUE)
    + ylab(TeX(paste("Deslocamento", parens(ph.TeX.deslocamento))))
    + xlab(TeX(paste("Tempo", parens(ph.TeX.tempo))))
    + xlim(c(0.0, 8.0))
    + ylim(c(-0.0, 2.2))
  )
```

```{r, fig.width=6, fig.height=3.5, echo=FALSE}
# Analise de velocidade, derivada
velocidade_line = deriv(curve)
velocidades = as.function(velocidade_line)(dados.MUV)
colnames(velocidades) = TeX(paste(subscript("v", 1:ncol(dados.MRU)), parens(ph.TeX.velocidade)))
x = seq(0.0, 8.0, length.out=30)
y = as.function(velocidade_line)(x)

angle_label = paste0("$\\theta = ", round(rad2deg(velocidade_line[2]), digits=2), "°$")
angle_aes = aes(x=2.0, y=0.02, 
                label=TeX(angle_label, output="character"))

x_points = flatten_by_rows(dados.MUV)
y_points = as.function(velocidade_line)(x_points)
label_points = round(y_points, digits=2)
curve_text = paste("Velocidade:", polys(round(velocidade_line, digits=3), "t"))

grid.arrange(
  top="Velocidade x Tempo",
  ggplot(mapping=aes(x=x_points, y=y_points)) 
    + geom_line(aes(x=x, y=y))
    + geom_text(angle_aes, parse = TRUE)
    + geom_point()
    + geom_text(aes(label=label_points, hjust=0.5, vjust=-1.2))
    + geom_text(aes(x=0.5, y=0.9, label=curve_text, hjust=0.0, vjust=0), parse=TRUE)
    + ylab(TeX(paste("Velocidade", parens(ph.TeX.velocidade))))
    + xlab(TeX(paste("Tempo", parens(ph.TeX.tempo))))
    + xlim(c(0.0, 8.0))
    + ylim(c(0.0, 1.0))
  )
```


```{r, fig.width=7, fig.height=4, echo=FALSE}
deslocamento_curve = curve
# Analise de energia cinetica
cinetica_curve = ph.e.cinetica(velocidade_line, p.massa)

x_points = flatten_by_rows(dados.MUV)
y_points = as.function(cinetica_curve)(x_points)
label_points = round(y_points, digits=3)

x = seq(0.0, 8.0, length.out=30)
y = as.function(cinetica_curve)(x)

curve_text = paste("Cinética:", polys(round(cinetica_curve, digits=6), "t"))

# Analise de energia potencial (experimental)
pot_curve = ph.e.potencial(p.massa, p.MUV.h(deslocamento_curve))
pot_y = as.function(pot_curve)(x)
pot_y_points = as.function(pot_curve)(x_points)
pot_y_labels = round(pot_y_points, digits=3)
pot_curve_text = paste("Potencial:", polys(round(pot_curve, digits=6), "t"))

grid.arrange(top="Energia x Tempo", 
   ggplot(mapping=aes(x=x_points, y=y_points)) 
    + geom_line(aes(x=x, y=y, colour="Cinética"))
    + geom_line(aes(x=x, y=pot_y, colour="Potencial"))
    + geom_point()
    + geom_point(aes(y=pot_y_points, colour="Potencial"))
    + geom_text(aes(label=label_points, hjust=0.5, vjust=-1.2))
    + geom_text(aes(y=pot_y_points, label=pot_y_labels, hjust=0.5, vjust=-1.2, colour="Potencial"))
    + geom_text(aes(x=0.5, y=0.036, label=curve_text, hjust=0.0, vjust=0), parse=TRUE)
    + geom_text(aes(x=0.5, y=0.032, label=pot_curve_text, hjust=0.0, vjust=0, colour="Potencial"), parse=TRUE)
    + ylab(TeX(paste("Energia", parens(ph.TeX.energia))))
    + xlab(TeX(paste("Tempo", parens(ph.TeX.tempo))))
    + xlim(c(0.0, 8.0))
    + ylim(c(0.0, 0.04))
    + scale_colour_manual("", values=c("Cinética"="black", "Potencial"="red"))
   )
```
